project:
  type: website

website:
  title: "Renee DeMaio"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: tabs/about/about.ipynb
        text: About Me
      - href: tabs/introduction/introduction.ipynb
        text: Introduction
      - href: https://github.com/anly501/dsan-5000-project-rennyd123
        text: Code
      - text: Data
        menu: 
          - href: https://github.com/anly501/dsan-5000-project-rennyd123/tree/main/data
            text: Data
          - href: tabs/data_gathering/data.ipynb
            text: Data Gathering
          - href: tabs/data_cleaning/data_cleaning.ipynb
            text: Data Cleaning
          - href: tabs/eda/eda.ipynb
            text: Data Exploration
      - href: tabs/clustering/clustering.ipynb
        text: Clustering
      - href: tabs/dimensionality_reduction/dimensionality_reduction.ipynb
        text: Dimensionality Reduction
      - href: tabs/naive_bayes/naive_bayes.ipynb
        text: Naive Bayes 
      - href: tabs/decision_tree/classification.ipynb
        text: Decision Trees
      - href: tabs/conclusion/conclusion.ipynb
        text: Conclusions

  page-footer:
    background: light 
    left: 
      - "Copyright 2023, Renee DeMaio"
    right: 
      - icon: github 
        href: https://github.com/anly501/dsan-5000-project-rennyd123

bibliography: SI-references.bib

format:
  html:
    smooth-scroll: true
    theme: 
        - styles.scss
    mainfont: Gilda Display
    toc: true
    link-external-newwindow: true 
    citations-hover: true
    footnotes-hover: true
    plotly:
      include: true



